# .github/workflows/trigger-supabase-scheduler.yml

name: Trigger Supabase Post Scheduler

on:
  schedule:
    # Roda a cada 5 minutos.
    # Para rodar a cada 1 minuto, use: '* * * * *'
    - cron: "*/5 * * * *"
  workflow_dispatch: # Permite rodar manualmente pela interface do GitHub

jobs:
  invoke-scheduler-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -i -X POST "${{ secrets.SUPABASE_FUNCTION_URL }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
